name: Add an animation
description: Propose a new animation to be included.
title: "[New animation] "
labels: ["enhancement"]
assignees:
  - Silejonu
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to expand the collection!
  - type: textarea
    id: animation
    attributes:
      label: Animation
      description:
        "Enter the animation(s) you'd like to be included (one per line)
        
        format: `animation_name=( interval_between_each_frame 'frame 01' 'frame 02' 'frame 03' 'frame 04' )`
        
        * The interval between each frame must be a number and is expressed in seconds.
        
        * You can include as little or as much frames as you want (well, maybe not 1 or 999!).
        
        * Each frame must be separated by a space.
        
        * Do not quote the frames unless you need to, in which case, use single-quotes.
        
        * If you must include spaces in your animation, use **non-breaking spaces** (U+00A0), and single-quote each frame.
        
        * All frames in a single animation **must** be of equal width.
        
        * Add non-breaking spaces to overwrite the characters from the last frame."
        
      render: shell
      placeholder:
        bubble=( 0.6 · o O O o · )
        
        arrow=( 0.15 ▹▹▹▹▹ ▸▹▹▹▹ ▹▸▹▹▹ ▹▹▸▹▹ ▹▹▹▸▹ ▹▹▹▹▸ ▹▹▹▹▹ ▹▹▹▹▹ ▹▹▹▹▹ ▹▹▹▹▹ ▹▹▹▹▹ ▹▹▹▹▹ ▹▹▹▹▹ )
        
        bomb=( 0.25 '💣   ' ' 💣  ' '  💣 ' '   💣' '   💣' '   💣' '   💣' '   💣' '   💥' '    ' '    ' )
