name: Add an animation
description: Propose a new animation to be included.
title: "[New animation] "
labels: ["enhancement"]
assignees: Silejonu
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to expand the collection!
  - type: textarea
    id: animation
    attributes:
      label: Animation
      description: "Enter the animation(s) you'd like to be included"
      render: shell
      placeholder: animation_name=( 'frame 01' 'frame 02' 'frame 03' 'frame 04' )
        You can include as little or as much frames as you want (well, maybe not 1 or 999!).
