name: Report a broken animation.
description: Report a display issue with an existing animation
title: "[Broken animation] "
labels: ["bug"]
assignees:
  - Silejonu
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to improve the collection!
  - type: checkboxes
    id: download-method
    attributes:
      label: Download method
      description: Make sure to download the script via
        `git clone https://github.com/Silejonu/bash_loading_animations`
        or `wget https://raw.githubusercontent.com/Silejonu/bash_loading_animations/main/bash_loading_animations.sh`
        If you did not, **broken animations are to be expected**, as doing otherwise will convert the non-breaking spaces to regular spaces.
      options:
        - label: I used one of the above methods to download the script, and I still have an issue.
          required: true
  - type: input
    id: affected-animation
    attributes:
      label: Affected animation
      description: If you found that several animations have issues, please fill a separate bug report for each of them.
      placeholder: ex. classic
    validations:
      required: true
  - type: input
    id: terminal
    attributes:
      label: Terminal used
      placeholder: ex. GNOME Terminal, Alacritty, st, Konsole, TTY…
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: ex. Ubuntu, Fedora, macOS, WSL…
    validations:
      required: true
  - type: dropdown
    id: unicode
    attributes:
      label: UTF-8 support
      description: Please verify that your terminal supports UTF-8. Check the output of `echo -e '\xe2\x82\xac'`. If you see `€` then it is working correctly. If not, you may need to enable UTF-8 support or use a font with a wider range of supported characters.
      options:
        - My terminal does indeed support UTF-8
        - I want to report an issue with an ASCII animation
    validations:
      required: true
  - type: input
    id: font
    attributes:
      label: Terminal font
      placeholder: ex. Noto Sans Mono, JetBrains Mono, D2Coding, Hack, DejaVu Sans Mono…
    validations:
      required: true
  - type: textarea
    id: additional-comments
    attributes:
      label: Additional comments
      description: Anything else? Please tell us!
      placeholder: ex. The animation `foo` does not loop correctly. 
    validations:
      required: false
