name: Submit an animation
description: Propose a new animation to be included.
title: "[New animation] "
labels: ["enhancement"]
assignees:
  - Silejonu
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to expand the collection!
        Describe the animation(s) you'd like to be included, or directly submit them with the appropriate syntax.
        Feel free to open a pull request if you prefer: just make sure to follow the guidelines described below.
  - type: textarea
    id: syntax
    validations:
      required: true
    attributes:
      label: Animation(s)
      description:
        "`animation_name=( interval_between_each_frame 'frame 01' 'frame 02' 'frame 03' 'frame 04' )`
        
        * `interval_between_each_frame` is a number, expressed in seconds.
        
        * You can include as little or as much frames as you want (well, maybe not 1 or 999!).
        
        * Each frame must be separated by a space.
        
        * Do not quote the frames unless you need to, in which case, use single-quotes.
        
        * If you must include spaces in your animation, use **non-breaking spaces** (U+00A0), and single-quote each frame.
        
        * All frames in a single animation **must** be of equal width. Add non-breaking spaces to fill the gaps."
        
      render: shell
      placeholder:
        bubble=( 0.6 · o O O o · )
        
        arrow=( 0.15 ▹▹▹▹▹ ▸▹▹▹▹ ▹▸▹▹▹ ▹▹▸▹▹ ▹▹▹▸▹ ▹▹▹▹▸ ▹▹▹▹▹ ▹▹▹▹▹ ▹▹▹▹▹ ▹▹▹▹▹ ▹▹▹▹▹ ▹▹▹▹▹ ▹▹▹▹▹ )
        
        bomb=( 0.25 '💣   ' ' 💣  ' '  💣 ' '   💣' '   💣' '   💣' '   💣' '   💣' '   💥' '    ' '    ' )
